[package]
name = "assimilate_bin"
version = "0.1.0"
authors = ["Vern Hockney <fred@vernhockney.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.15"

